config/routes.rb
Rails.application.routes.draw do

  root to:'toppages#index'
  get 'signup', to: 'users#new'
   
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
   get 'signup', to: 'users#new'
  
  
  resources :users, only: [:new, :create] do
    collection do
      get 'mypage'
    end
  end
  resources :users, only: [:index, :show, :new, :create]
  resources :messages, only: [:index, :create,:new, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @messages = Message.all
  end  
  
  def new 
    @message = Message.new
  end  
  
  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @messages = current_user.messages.order(id: :desc).page(params[:page])
      flash.now[:danger] = '投稿に失敗しました。'
      render 'toppages/index'
    end  
  end

  def edit
    @message = Message.find(params[:id])
  end
  
  def update
     @message = Message.find(params[:id])

    if @message.update(message_params)
      flash[:success] = 'Message は正常に更新されました'
      redirect_to mypage_users_path
    else
      flash.now[:danger] = 'Message は更新されませんでした'
      render :edit
    end
  end  

  def destroy
    @message.destroy
    flash[:success] = '削除しました。'
    redirect_back(fallback_location: root_path)
  end
end

  private

  def message_params
    params.require(:message).permit(:title, :content)
  end
  
  def correct_user
    @message = current_user.messages.find_by(id: params[:id])
    unless @message
      redirect_to root_url
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      
      @messages = Message.all.order(id: :desc).page(params[:page])
      @users = User.all.order(id: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show, :mypage]
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(25)
  end
  def show
    @user = User.find(params[:id])
    @messages = @user.messages.order(id: :desc).page(params[:page])
  end
  
  def mypage
    @messages = current_user.messages
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private
  
  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">messages</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
       <% if logged_in? %>
        <li class="nav-item"><%= link_to 'Mypage', mypage_users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
       <% else %> 
        <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
       <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Originalmessages</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>
    
      <%= yield %>
    </div>  
  </body>
</html>

app/views/messages/edit.html.erb
<h1>message編集</h1>

<%= form_with(model: @message, local: true) do |f| %>
  <%= f.label :title, 'title' %>
  <%= f.text_field :title %>
  <%= f.label :content, 'message' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to 'Mypageに戻る', mypage_users_path %>

app/views/messages/index.html.erb
<h1>message</h1>
<div class="col-md-4 offset-md-4">
  <ul>
    <% @messages.each do |message| %>
      <li><%= message.content %></li>
    <% end %>
  </ul>_
</div>

app/views/messages/new.html.erb
<h3>message新規作成</h3>

<%= form_with(model: @message, local: true) do |f| %>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title %>
  <%= f.label :content, 'Message' %>
  <%= f.text_field :content %>

  <%= f.submit '投稿' %>
<% end %>

<%= link_to 'トップページに戻る', root_path %>
<%= link_to 'Mypageに戻る', mypage_users_path %>

app/views/toppages/index.html.erb
<% if logged_in? %>
<h1>Everyone's messages</h1>
 <%= link_to 'New message', new_message_path, class: 'btn btn-lg btn-primary' %>
  <div class="row">
    <div class="col-md-10">
      <table class="table table-striped">
        <thead class="thread-light">
          <tr>
            <th>Title</th>
            <th>Message</th>
          </tr>
        </thead>
        <tbody>
          <% @messages.each do |message| %>
            <tr>
              <td><%= message.title %></td>
              <td><%= message.content %></td>
               <% end %>
            </tr>
        </tbody>
      </table>
    </div>
   </div>
<% else %>
   <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the messages</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
   </div>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/mypage.html.erb
<h1>My messages</h1>
<%= link_to 'New message', new_message_path, class: 'btn btn-lg btn-primary' %>
  
    <table class="table table-striped">
       <thead class="thread-light">
          <tr>
            <th>Title</th>
            <th>Message</th>
            <th>Edit/Delete</th>
          </tr>
        </thead>
        <tbody>
          <% @messages.each do |message| %>
            <tr>
              <td><%= message.title %></td>
              <td><%= message.content %></td>
              <td><%= link_to'Edit', edit_message_path(message)%>
                  <%= link_to'Delete', message_path(message), method: :delete, data:{ confirm: 'Sure?' } %></td>
            </tr>
          <% end %>
         </tbody>
    </table>  
  

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %> 
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %> messages</h1>
<div class="row">
  <div class="col-md-10">
    <table class="table table-striped">
       <thead class="thread-light">
          <tr>
            <th>Title</th>
            <th>Message</th>
          </tr>
        </thead>
        <tbody>
          <% @messages.each do |message| %>
            <tr>
              <td><%= message.title %></td>
              <td><%= message.content %></td>
            </tr>
          <% end %>
         </tbody>
    </table>  
  </div>
</div>